# EXT:pagetreefixer/Configuration/Services.yaml
services:

  KayStrobach\PageTreeFixer\Command\FixOrphanedPagesCommand:
    tags:
      - name: 'console.command'
        command: 'pagetreefixer:fixorphanedpages'
